### ISSUE TITLE
conversion stopped @11%  

### ISSUE THREAD

**Issue by TemplarB** [aedocw/epub2tts-edge#45]
I've made a few audiobooks before using this script and all worked great. Today after like a two-week hiatus I decided to create another audio. The first try went to % bar but never passed a bit. I ran the update, restarted, now it is stuck @11% for an hour
![Screenshot 2024-12-01 125104](https://github.com/user-attachments/assets/2e8770b0-de2c-4376-80e8-98b256654ba9)

**Comment by TemplarB** [comment]
Later the same day it worked ok with the same text and settings. Possibly it was an issue on tts provider side

**Comment by aedocw** [comment]
Yes, this is most likely an issue with the remote API (Microsoft Edge) that creates the audio. Sometimes local networking issues can cause this if the remote server is unavailable, or else something on the Edge server side.

It would start back up at 11% and seem to be stalled there because the temp files were there, so epub2tts-edge tried to start over where it left off.

If this happens again, first confirm network connectivity and DNS are working properly. Then remove the temp files and try running epub2tts-edge again. If you find you are able to reproduce the problem, please reopen this issue with details on how you are able to recreate the issue.
